version: "3.9"
services:
  mysql8:
    image: mysql:8.3.0
    container_name: mysql8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_management
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - e-commerce-backend-java
  users:
    build:
      context: ./
      dockerfile: ./users-service/Dockerfile
    container_name: users-service
    ports:
      - "8001:8001"
    env_file: ./users-service/.env
    depends_on:
      - mysql8
    restart: always
    networks:
      - e-commerce-backend-java
volumes:
  data-mysql:
    name: data-mysql
networks:
  e-commerce-backend-java:
    name: e-commerce-backend-java